### ISSUE TITLE
Fails when used whith blueimp/nightwatch docker setup

### ISSUE THREAD

**Issue by enjikaka** [blueimp/geckodriver#1]
Replacing chromedriver with geckodriver in blueimp/nightwatch throws this error;

```
Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ value:
   { error: 'unknown command',
     message: 'POST /wd/hub/session did not match a known command',
     stacktrace: '' } }
```

Have any usage information for this repo? :)

**Comment by blueimp** [comment]
Sorry for the late reply @enjikaka, I completely missed this issue.

Nightwatch.js still doesn't properly support the W3C Webdriver API, which is required by geckodriver.
I've posted an issue to their tracker here:
https://github.com/nightwatchjs/nightwatch/issues/1285

However geckodriver works very well with [Webdriver.io](https://webdriver.io/) and I've created a sample project that uses Webdriver.io with Docker and this geckodriver image here:
https://github.com/blueimp/wdio

**Comment by enjikaka** [comment]
@blueimp Thanks. I'll have a look!
